### STAGE 1: Build ###
FROM node:latest AS build
WORKDIR /app
COPY package*.json /app/
RUN npm install
COPY ./ /app/
ARG configuration=k3d
RUN npm run build -- --output-path=./dist/out --configuration $configuration
### STAGE 2: Run ###
FROM nginx:alpine
COPY --from=build /app/dist/out/ /usr/share/nginx/html
#Copy default nginx configuration
COPY ./nginx.conf /etc/nginx/conf.d/default.conf